apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  jsonData:
      timeInterval: 60s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
          urlDisplayLabel: 'Trace: $${__value.raw}'
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  uid: tempo
  jsonData:
    tracesToLogsV2:
      customQuery: true
      datasourceUid: 'loki'
      query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
      tags:
        - key: 'service.name'
          value: 'service_name'
        
    serviceMap:
      datasourceUid: 'prometheus'
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: 'loki'
- name: Loki
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  jsonData:
    derivedFields:
      - name: 'trace_id'
        matcherType: 'label'
        matcherRegex: 'trace_id'
        url: '$${__value.raw}'
        datasourceUid: 'tempo'
        urlDisplayLabel: 'Trace: $${__value.raw}'